name: SonarQube Analysis

on:
  push:
    branches: [ main ]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: npx jest --coverage

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonarqube-scanner
          npx sonar-scanner \
            -Dsonar.projectKey=js-sonarqube-demo \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://192.168.7.77:9000 \
            -Dsonar.login=${SONAR_TOKEN}
